### ISSUE TITLE
[setup] 프로젝트 개발 환경 구축

### ISSUE THREAD

**Issue by kimhxsong** [ping-neo-meo-pong/pnmp#1]
## Description
본격적으로 개발을 진행하기에 앞서 개발 환경을 구축합니다. 도커파일 및 도커컴포즈 파일 작성은 진행했던 @kjh6b6a68 @minsikim-42 님이  [ping-neo-meo-pong/pong_toy](https://github.com/ping-neo-meo-pong/pong_toy)에서 작성한 도커파일과 @Jiwon-Woo 님이[ ping-neo-meo-pong/ts-docker](https://github.com/ping-neo-meo-pong/ts-docker) 에서 작성한 도커파일 및 도커컴포즈 파일을 참고합니다. 목록에 추가할 내용이 있다면 코멘트를 남겨주세요. 

## Todo
- [x] 깃 커밋 메시지 및 브랜치 이름에 대한 깃훅 설정 (10.29 ~ 10.30)
- [ ] ~~도커파일/ 도커컴포즈 파일 추가~~
- [ ] ~~airbnb 린트 도구 적용~~
