### ISSUE TITLE
[feat] 플레이어가 게임 중간에 나갔을때

### ISSUE THREAD

**Issue by minsikim-42** [ping-neo-meo-pong/pnmp#10]
## Description
플레이어가 중간에 나갔을때 시간초를 두어 이 안에 들어오지 못할경우 실격패가 되게 합니다.
또한 시작전에도 약 3초간의 대기시간을 두려합니다.

## Todo
- [x] 나간 유저가 플레이어면 게임 중지
- [x] 중지된 게임은 시간안에 플레이어가 들어오지 못할경우 실격패
- [x] 시작전 3초가량의 대기시간
- [x] 게임 코드로직 리펙토링

**Comment by kimhxsong** [comment]
전에 회의했을 때 연결이 끊어지면 게임은 진행되지만 상대방 커서는 움직이지 않은 것으로 하고 재접속 때 이어서 진행할 수 있도록 이야기 했던 것 같은데, 실격패보다 상대방 위치를 갱신하지 않게하고 게임 모드에 따른 승패 판정 알고리즘에 의해 게임이 끝나는 것이 좀 더 단순하지 않을까요?

**Comment by minsikim-42** [comment]
그럴것 같네요 ㅎㅎ; 평가표를 잘못 생각해서 뭔가 상대방이 나가면 멈춰야한다고 생각했던것 같아요 ㅎㅎ
그런데 사실 이슈를 날리기 전부터 꽤나 구현을 해놓았고 어제 지환님이랑 거의 마쳤거든요 허헣,,
오류가 몇 있기는 해서 이게 잘 잡히면 그대로 진행하고 어렵겠다 싶으면 말씀대로 단순히 처리해도 될까요?

**Comment by minsikim-42** [comment]
그럴것 같네요 ㅎㅎ; 잘못 생각해서 뭔가 상대방이 나가면 멈춰야한다고 생각했던것 같아요 ㅎㅎ
그런데 사실 이슈를 날리기 전부터 꽤나 구현을 해놓았고 어제 지환님이랑 거의 마쳤거든요 허헣,,
오류가 몇 있기는 해서 이게 잘 잡히면 그대로 진행하고 어렵겠다 싶으면 말씀대로 단순히 처리해도 될까요?
