### ISSUE TITLE
[feat] 게임 초대시 게임 리스트에 등록, 게임 종료시 히스토리에 등록

### ISSUE THREAD

**Issue by minsikim-42** [ping-neo-meo-pong/pnmp#15]
## Description
게임 초대시 alert, confirm 대신 게임 리스트에 등록되도록 함.
게임 종료시 게임 정보가 히스토리에 등록

## Todo
- [ ] 게임 초대시 alert, confirm 대신 게임 리스트에 등록되도록 함.
- [ ] 리스트 다시 불러오는 버튼
- [ ] 게임 종료시 게임 정보가 히스토리에 등록.
