### ISSUE TITLE
[feat] 채널 페이지

### ISSUE THREAD

**Issue by kjh6b6a68** [ping-neo-meo-pong/pnmp#28]
## Description
채널 페이지를 만듭니다.

## Todo
- [x] 채널에 참여한 유저 목록
- [x] 채널에 유저 초대
- [x] 참여한 유저를 ban, mute 하거나 권한을 부여할수 있는 버튼/모달 등등
- [x] 채널 비밀번호를 바꿀수 있는 기능
