### ISSUE TITLE
[feat] user_data, is_player 삭제, live&readerboard 페이지 생성 & 래더점수 개혁

### ISSUE THREAD

**Issue by minsikim-42** [ping-neo-meo-pong/pnmp#31]
## Description
새로고침이후 user_data가 초기화되므로 user_data를 import할 필요가 없음
is_player는 이제 필요없는 변수(게임페이지에서 플레이어인지 확인)
live페이지
리더보드페이지 -> ladder점수 개혁필요, 1승마다 1점식 오르고 매칭레벨은 n / 10으로 대충 떼울까 생각중

## Todo
- [x] user_data not import
- [x] delete is_player
- [x] 대충 live 페이지
- [x] 대충 래더점수 개혁
- [x] 대충 readerboard 페이지
