### ISSUE TITLE
[feat] github 로그인 없애기

### ISSUE THREAD

**Issue by Jiwon-Woo** [ping-neo-meo-pong/pnmp#78]
## Description
프론트 리팩토링

## Todo
- [ ] github 로그인 없애기
- [ ] eslint 적용
- [ ] == 를 === 로 바꾸기
- [ ] catch console.log 변경
- [ ] import 및 안쓰는 거 없애기
